var initx;initx=screen.availWidth/2-200;Ext.getCmp("mainPanel").showAt(initx,100);function refresh(a,b){b.src="../imageServlet?"+Math.random()}function getCookie(a){var b=a+"=";if(0<document.cookie.length)return a=document.cookie.indexOf(b),-1!=a?(a+=b.length,b=document.cookie.indexOf(";",a),-1==b&&(b=document.cookie.length),unescape(document.cookie.substring(a,b))):null}var locale=getCookie("locale");
null==locale||void 0==locale?window.location="login_locale.action?language=zh&country=cn":locale=locale.replace(/-/,"_").toLowerCase();var localeRadio=Ext.getCmp("locale_radiogroup");localeRadio.setValue({lo:[locale]});var isChecked=!0;function switchLocale(a){isChecked&&(isChecked=!1,a=a.inputValue.split("_"),window.location="login_locale.action?language="+a[0]+"&country="+a[1])}var checkActionSending=!1;
function check(){var a=loginForm.getForm();if(a.isValid()){var b=Ext.getCmp("username").getValue(),c=Ext.getCmp("password").getValue(),d=Ext.getCmp("randomCode").getValue(),e=Ext.Msg.wait("${app:i18n_def('msg.wait.show','Please waiting ......')}");checkActionSending||(checkActionSending=!0,Ext.Ajax.request({url:"checkPassword.action",params:{username:b,password:c,randomCode:d},callback:function(b,c,d){checkActionSending=!1;e.hide();c?(b=Ext.decode(d.responseText).msg,"0"!=b?failure(b):login()):(Ext.MessageBox.alert("${app:i18n('prompt')}",
"${app:i18n('login.timeout')}"),a.findField("password").setValue(""))}}))}else focus()}
function login(){if(loginForm.getForm().isValid()){var a=Ext.getCmp("username").getValue(),b=Ext.getCmp("password").getValue(),c=Ext.getCmp("randomCode").getValue(),d=Ext.Msg.wait("${app:i18n_def('msg.wait.show','Please waiting ......')}");Ext.Ajax.request({url:"login.action",params:{username:a,password:b,randomCode:c},callback:function(a,b,c){d.hide();b?(a=Ext.decode(c.responseText).msg,"0"!=a?(Ext.getCmp("randomCodeValid").getEl().dom.src="../imageServlet?"+Math.random(),failure(a)):(Ext.Msg.wait("${app:i18n_def('msg.wait.show','Please waiting ......')}"),
"pms"==window.name?window.location="frame.action":(window.open("","_self",""),window.opener=null,(a=window.open("frame.action","pms","channelmode=1,resizable=1,status=1"))?(a.focus(),window.close()):window.location.href="frame.action"))):(Ext.MessageBox.alert("${app:i18n('prompt')}","${app:i18n('login.timeout')}"),Ext.getCmp("password").setValue(""))}})}else focus()}
function failure(a){"1"==a?Ext.MessageBox.alert("${app:i18n('prompt')}","${app:i18n('Authorize.not.exist.user')}"):"2"==a?Ext.MessageBox.alert("${app:i18n('prompt')}","${app:i18n('Authorize.invalid.user')}"):"3"==a?Ext.MessageBox.alert("${app:i18n('prompt')}","${app:i18n('Authorize.illegal.username')}"):"4"==a?Ext.MessageBox.alert("${app:i18n('prompt')}","${app:i18n('Authorize.illegal.password')}"):"5"==a?Ext.MessageBox.alert("${app:i18n('prompt')}","${app:i18n('Authorize.error.password')}"):"6"==
a?Ext.MessageBox.alert("${app:i18n('prompt')}","${app:i18n('Authorize.error')}"):"7"==a?Ext.MessageBox.alert("${app:i18n('prompt')}","${app:i18n('Authorize.not.accredit')}"):"8"==a&&Ext.MessageBox.alert("${app:i18n('prompt')}","${app:i18n('Authorize.illegal.randomCodeException')}");Ext.getCmp("password").setValue("")}function focus(a,b){Ext.getCmp("username").getValue()?b&&b.getKey()==b.ENTER&&Ext.getCmp("password").focus():Ext.getCmp("username").focus()}Ext.getCmp("username").focus();
function enterKey(a,b){b&&b.getKey()==b.ENTER&&a.getValue()&&login()};
