function nvl(a,b){return a&&null!=a?a:b}String.prototype.trim=function(){return this.replace(/(^\s*)|(\s*$)/g,"")};String.prototype.ltrim=function(){return this.replace(/(^\s*)/g,"")};String.prototype.rtrim=function(){return this.replace(/(\s*$)/g,"")};String.prototype.endsWith=function(a){return RegExp(a+"$").test(this)};String.prototype.replaceAll=function(a,b){return this.replace(RegExp(a,"g"),b)};String.prototype.startsWith=function(a){return RegExp("^"+a).test(this)};
function CommMethod(){this.isEmpty=function(a){return CommMethod.isEmpty(a)}}CommMethod.isEmpty=function(a){return void 0==a||null==a||"null"==a||""==a?!0:!1};CommMethod.getNotNull=function(a,b){b||(b="");return this.isEmpty(a)?b:a};CommMethod.getNotNullHtml=function(a,b){return CommMethod.getNotNull(a,"&nbsp;")};CommMethod.nvl=function(a,b){return nvl(a,b)};CommMethod.trim=function(a){return a.trim()};CommMethod.ltrim=function(a){return a.ltrim()};CommMethod.rtrim=function(a){return a.rtrim()};
CommMethod.endsWith=function(a,b){return(""+a).endsWith(b)};CommMethod.startsWith=function(a,b){return(""+a).startsWith(b)};CommMethod.replaceAll=function(a,b,c){return(""+a).replaceAll(b,c)};CommMethod.showAttr=function(a){var b="",c;for(c in a)b=b+c+",\t";alert(b)};CommMethod.sort=function(a){for(var b=0;b<a.length;b++)for(var c=0;c<a.length;c++)if(a[b]<a[c]){var d=a[b];a[b]=a[c];a[c]=d}return a};
CommMethod.distinct=function(a){if(a instanceof Array){this.sort(a);for(var b=[],c=0,d=0;d<a.length;d++)a[d]!=c&&(c=a[d],b.push(a[d]));return b}a=a.split(",");this.sort(a);a=this.distinct(a);b="";for(d=0;d<a.length;d++)b+=a[d]+",";0<a.length&&(b=b.substring(0,b.length-1));return b};CommMethod.showObj=function(a){var b="",b=this.obj2str(a);alert(b)};CommMethod.obj2json=function(a,b){var c=CommMethod.obj2str(a,b);eval("var oper="+c);return oper};
CommMethod.obj2strln=function(a,b){var c=this.obj2str(a,b),d="#";if(0>c.indexOf(d))return c=CommMethod.replaceAll(c,",",d),CommMethod.replaceAll(c,d,",\n");d="zzz";if(0>c.indexOf(d))return c=CommMethod.replaceAll(c,",",d),CommMethod.replaceAll(c,d,",\n");d="xxx";0>c.indexOf(d)&&(c=CommMethod.replaceAll(c,",",d),c=CommMethod.replaceAll(c,d,",\n"));return c};
CommMethod.obj2str=function(a,b){var c=[],d;if("string"==typeof a)return"'"+a.replace(/([\'\"\\])/g,"\\$1").replace(/(\n)/g,"\\n").replace(/(\r)/g,"\\r").replace(/(\t)/g,"\\t")+"'";if(null!=a&&"object"==typeof a){if(a.sort){for(e=0;e<a.length;e++)d=a[e],d instanceof Date?c.push(d.format("yyyy-MM-dd hh:mm:ss")):c.push(d);c="["+c.join()+"]"}else{for(var e in a)d=a[e],d instanceof Date?b?c.push("'"+b+"."+e+"':'"+this.obj2str(d.format("yyyy-MM-dd hh:mm:ss"))+"'"):c.push(e+":"+this.obj2str(d.format("yyyy-MM-dd hh:mm:ss"))+
""):b?c.push("'"+b+"."+e+"':"+this.obj2str(d)):c.push(e+":"+this.obj2str(d));document.all&&!/^\n?function\s*toString\(\)\s*\{\n?\s*\[native code\]\n?\s*\}\n?\s*$/.test(a.toString)&&c.push("toString:"+a.toString.toString());c="{"+c.join()+"}"}return c}return null!=a?a.toString():"null"};
CommMethod.array2str=function(a,b){if(a instanceof Array){for(var c="[",d,e=0;e<a.length;e++)d=a[e],c=d instanceof Number||d instanceof String||d instanceof Boolean?c+(d+","):d instanceof Date?c+(d+","):c+(CommMethod.obj2str(d)+","),!0==b&&(c+="\n");1<c.length&&(c=!0==b?c.substring(0,c.length-2):c.substring(0,c.length-1));return c+"]"}return"\u4e0d\u662f\u6570\u7ec4"};CommMethod.array2strln=function(a){return CommMethod.array2str(a,!0)};
CommMethod.getTypeof=function(a){return void 0===a?"undefined":null==a?"null":a instanceof Number?"Number":a instanceof String?"String":a instanceof Boolean?"Boolean":a instanceof Date?"Date":typeof a};CommMethod.allAreaWord=function(){try{var a=new ActiveXObject("Word.Application"),b=a.Documents.Add("",0,1).Range(0,1),c=document.body.createTextRange();c.moveToElementText(PrintA);c.select();c.execCommand("Copy");b.Paste();a.Application.Visible=!0}catch(d){alert("\u6b64\u529f\u80fd\u4ec5\u652f\u6301IE6\u4ee5\u4e0a\u6d4f\u89c8\u5668\u4f7f\u7528\uff0c\u8bf7\u4f7f\u7528IE\u540e\u518d\u8bd5\u3002")}};
CommMethod.allAreaExcel=function(){try{var a=new ActiveXObject("Excel.Application"),b=a.Workbooks.Add().ActiveSheet,c=document.body.createTextRange();c.moveToElementText(PrintA);c.select();c.execCommand("Copy");b.Paste();a.Visible=!0}catch(d){alert("\u6b64\u529f\u80fd\u4ec5\u652f\u6301IE6\u4ee5\u4e0a\u6d4f\u89c8\u5668\u4f7f\u7528\uff0c\u8bf7\u4f7f\u7528IE\u540e\u518d\u8bd5\u3002")}};CommMethod.printDiv=function(a,b){$("#"+a).css("display","none");$("div#"+b).jqprint();$("#"+a).css("display","block")};
CommMethod.printArray=function(a){var b="";0<a.length&&(b=CommMethod.getTypeof(a[0]));alert(b+"[]--"+CommMethod.array2strln(a))};CommMethod.getCssPxValue=function(a){return 0<a.indexOf("px")?(a=a.substring(0,a.length-2),Number(a)):a};CommMethod.getParamsOfObj=function(a,b){var c="";void 0!=b&&null!=b&&""!=b&&(c=b+".");var d=[];for(i in a)a.hasOwnProperty(i)&&null!=a[i]&&""!=a[i]&&d.push("&"+c+i+"="+(null!=a[i]?a[i]:"null"));return d.join("")};
Array.prototype.del=function(a){for(var b=0;b<this.length;b++)a==this[b]&&this.remove(b)};Array.prototype.remove=function(a){if(isNaN(a)||a>this.length)return!1;for(var b=0,c=0;b<this.length;b++)this[b]!=this[a]&&(this[c++]=this[b]);this.length-=1};
